import java.io.IOException;
import java.math.BigDecimal;
import java.security.PublicKey;
import java.time.LocalDate;
import java.util.Scanner;

import BUS.BookFormatsBUS;
import BUS.BooksBUS;
import BUS.CustomersBUS;
import BUS.EmployeesBUS;
import BUS.GenresBUS;
import BUS.MidForBooksBUS;
import BUS.PublishersBUS;
import BUS.StaTypesBUS;
import BUS.StationeriesBUS;
import BUS.SuppliersBUS;
import BUS.TypesBUS;
import DTO.BookFormats;
import DTO.BookGenres;
import DTO.BookTypes;
import DTO.Books;
import DTO.Customers;
import DTO.Employees;
import DTO.Publishers;
import DTO.Suppliers;

public class App {
        Scanner input = new Scanner(System.in);

        public static void main(String[] args) throws IOException {
                // !INIT OBJ
                MidForBooksBUS testArray = new MidForBooksBUS();
                GenresBUS initList = new GenresBUS();
                TypesBUS testList = new TypesBUS();
                StaTypesBUS newTest = new StaTypesBUS();
                PublishersBUS testPublishers = new PublishersBUS();
                BookFormatsBUS listFormat = new BookFormatsBUS();
                StationeriesBUS listSta = new StationeriesBUS();
                BooksBUS listBooks = new BooksBUS();
                CustomersBUS cusList = new CustomersBUS();
                EmployeesBUS empList = new EmployeesBUS();
                SuppliersBUS supList = new SuppliersBUS();

                // *READ FILE
                initList.readFile();
                testList.readFile();
                testPublishers.readFile();
                listFormat.readFile();
                supList.readFile();

                // !INIT ARRAY
                Books[] books = {
                                new Books("00110011", "Đỉnh Cao Mới", LocalDate.of(2022, 1, 15),
                                                new BigDecimal("100000"), 50, PublishersBUS.getPublishersList()[5],
                                                "Nguyễn Nhật Ánh", TypesBUS.getTypesList()[3],
                                                BookFormatsBUS.getFormatsList()[7], "15 x 20 cm",
                                                GenresBUS.getGenres(0, 4)),
                                new Books("00110012", "Cuộc Phiêu Lưu Bí Ẩn", LocalDate.of(2021, 6, 25),
                                                new BigDecimal("80000"), 80, PublishersBUS.getPublishersList()[3],
                                                "Trương Quỳnh", TypesBUS.getTypesList()[10],
                                                BookFormatsBUS.getFormatsList()[5], "13 x 18 cm",
                                                GenresBUS.getGenres(5, 9)),
                                new Books("00110013", "Hành Trình Tự Do", LocalDate.of(2020, 9, 30),
                                                new BigDecimal("95000"), 120, PublishersBUS.getPublishersList()[1],
                                                "Ngô Thanh Tùng", TypesBUS.getTypesList()[0],
                                                BookFormatsBUS.getFormatsList()[3], "20 x 25 cm",
                                                GenresBUS.getGenres(10, 15)),
                                new Books("00110014", "Khám Phá Vũ Trụ", LocalDate.of(2023, 5, 17),
                                                new BigDecimal("200000"), 60, PublishersBUS.getPublishersList()[7],
                                                "Lê Hoàng Nam", TypesBUS.getTypesList()[6],
                                                BookFormatsBUS.getFormatsList()[15], "10 x 14 cm",
                                                GenresBUS.getGenres(20, 25)),
                                new Books("00110015", "Câu Chuyện Cổ Tích", LocalDate.of(2019, 3, 12),
                                                new BigDecimal("75000"), 150, PublishersBUS.getPublishersList()[9],
                                                "Phạm Bảo Hân", TypesBUS.getTypesList()[4],
                                                BookFormatsBUS.getFormatsList()[6], "14 x 18 cm",
                                                GenresBUS.getGenres(5, 9)),
                                new Books("00110016", "Những Cuộc Chiến Lịch Sử", LocalDate.of(2021, 8, 1),
                                                new BigDecimal("130000"), 90, PublishersBUS.getPublishersList()[4],
                                                "Trần Minh Thắng", TypesBUS.getTypesList()[2],
                                                BookFormatsBUS.getFormatsList()[0], "18 x 23 cm",
                                                GenresBUS.getGenres(15, 20)),
                                new Books("00110017", "Cuộc Sống Vui Vẻ", LocalDate.of(2020, 7, 22),
                                                new BigDecimal("60000"), 200, PublishersBUS.getPublishersList()[2],
                                                "Lê Thanh Sơn", TypesBUS.getTypesList()[9],
                                                BookFormatsBUS.getFormatsList()[12], "13 x 18 cm",
                                                GenresBUS.getGenres(10, 15)),
                                new Books("00110018", "Bí Mật Về Nền Văn Hóa", LocalDate.of(2022, 11, 5),
                                                new BigDecimal("85000"), 75, PublishersBUS.getPublishersList()[0],
                                                "Nguyễn Văn A", TypesBUS.getTypesList()[8],
                                                BookFormatsBUS.getFormatsList()[19], "22 x 30 cm",
                                                GenresBUS.getGenres(25, 29)),
                                new Books("00110019", "Nghệ Thuật Sống", LocalDate.of(2019, 9, 17),
                                                new BigDecimal("45000"), 120, PublishersBUS.getPublishersList()[6],
                                                "Bùi Minh Đức", TypesBUS.getTypesList()[0],
                                                BookFormatsBUS.getFormatsList()[4], "16 x 20 cm",
                                                GenresBUS.getGenres(0, 4)),
                                new Books("00110020", "Thế Giới Của Những Kẻ Mơ Mộng", LocalDate.of(2023, 2, 12),
                                                new BigDecimal("105000"), 130, PublishersBUS.getPublishersList()[8],
                                                "Hoàng Mai Lan", TypesBUS.getTypesList()[12],
                                                BookFormatsBUS.getFormatsList()[10], "15 x 19 cm",
                                                GenresBUS.getGenres(5, 9)),
                                new Books("00110021", "Chuyến Phiêu Lưu Ngoài Hành Tinh", LocalDate.of(2020, 10, 1),
                                                new BigDecimal("200000"), 60, PublishersBUS.getPublishersList()[10],
                                                "Trần Phú Tài", TypesBUS.getTypesList()[6],
                                                BookFormatsBUS.getFormatsList()[16], "20 x 25 cm",
                                                GenresBUS.getGenres(20, 25)),
                                new Books("00110022", "Tình Yêu Và Hạnh Phúc", LocalDate.of(2022, 5, 18),
                                                new BigDecimal("120000"), 110, PublishersBUS.getPublishersList()[7],
                                                "Nguyễn Ái Phương", TypesBUS.getTypesList()[11],
                                                BookFormatsBUS.getFormatsList()[2], "12 x 16 cm",
                                                GenresBUS.getGenres(0, 4)),
                                new Books("00110023", "Những Chuyến Du Lịch Lạ Kỳ", LocalDate.of(2019, 12, 15),
                                                new BigDecimal("95000"), 85, PublishersBUS.getPublishersList()[12],
                                                "Dương Minh Tiến", TypesBUS.getTypesList()[3],
                                                BookFormatsBUS.getFormatsList()[18], "13 x 18 cm",
                                                GenresBUS.getGenres(5, 9)),
                                new Books("00110024", "Bí Quyết Thành Công", LocalDate.of(2021, 1, 3),
                                                new BigDecimal("75000"), 180, PublishersBUS.getPublishersList()[3],
                                                "Lâm Bảo Anh", TypesBUS.getTypesList()[4],
                                                BookFormatsBUS.getFormatsList()[8], "16 x 22 cm",
                                                GenresBUS.getGenres(15, 20)),
                                new Books("00110025", "Cuộc Cách Mạng Khoa Học", LocalDate.of(2020, 7, 10),
                                                new BigDecimal("120000"), 65, PublishersBUS.getPublishersList()[1],
                                                "Hồ Anh Minh", TypesBUS.getTypesList()[10],
                                                BookFormatsBUS.getFormatsList()[11], "18 x 24 cm",
                                                GenresBUS.getGenres(20, 25)),
                                new Books("00110026", "Sự Thật Về Thế Giới", LocalDate.of(2023, 4, 23),
                                                new BigDecimal("95000"), 95, PublishersBUS.getPublishersList()[2],
                                                "Trần Minh Hoàng", TypesBUS.getTypesList()[7],
                                                BookFormatsBUS.getFormatsList()[9], "14 x 20 cm",
                                                GenresBUS.getGenres(10, 15)),
                                new Books("00110027", "Khám Phá Những Điều Kỳ Diệu", LocalDate.of(2019, 6, 5),
                                                new BigDecimal("95000"), 100, PublishersBUS.getPublishersList()[0],
                                                "Đặng Tiến Dũng", TypesBUS.getTypesList()[5],
                                                BookFormatsBUS.getFormatsList()[13], "16 x 21 cm",
                                                GenresBUS.getGenres(0, 5)),
                                new Books("00110028", "Đến Với Mơ Ước", LocalDate.of(2021, 10, 15),
                                                new BigDecimal("130000"), 70, PublishersBUS.getPublishersList()[6],
                                                "Bùi Thanh Sơn", TypesBUS.getTypesList()[12],
                                                BookFormatsBUS.getFormatsList()[1], "14 x 20 cm",
                                                GenresBUS.getGenres(5, 9)),
                                new Books("00110029", "Khám Phá Những Bí Ẩn Vũ Trụ", LocalDate.of(2023, 6, 8),
                                                new BigDecimal("110000"), 120, PublishersBUS.getPublishersList()[8],
                                                "Lê Văn Kiệt", TypesBUS.getTypesList()[6],
                                                BookFormatsBUS.getFormatsList()[7], "12 x 18 cm",
                                                GenresBUS.getGenres(10, 15)),
                                new Books("00110030", "Vũ Trụ Và Những Khám Phá Mới", LocalDate.of(2022, 8, 22),
                                                new BigDecimal("115000"), 90, PublishersBUS.getPublishersList()[4],
                                                "Hà Minh Quang", TypesBUS.getTypesList()[7],
                                                BookFormatsBUS.getFormatsList()[15], "18 x 24 cm",
                                                GenresBUS.getGenres(15, 20)),
                                new Books("00110031", "Chuyến Du Hành Vào Tương Lai", LocalDate.of(2021, 5, 16),
                                                new BigDecimal("95000"), 80, PublishersBUS.getPublishersList()[9],
                                                "Trần Minh Khải", TypesBUS.getTypesList()[3],
                                                BookFormatsBUS.getFormatsList()[4], "14 x 20 cm",
                                                GenresBUS.getGenres(0, 5)),
                                new Books("00110032", "Hành Trình Tìm Kiếm Bản Ngã", LocalDate.of(2020, 2, 11),
                                                new BigDecimal("80000"), 100, PublishersBUS.getPublishersList()[11],
                                                "Nguyễn Mạnh Cường", TypesBUS.getTypesList()[1],
                                                BookFormatsBUS.getFormatsList()[16], "12 x 18 cm",
                                                GenresBUS.getGenres(5, 9)),
                                new Books("00110033", "Khám Phá Tâm Hồn", LocalDate.of(2022, 9, 30),
                                                new BigDecimal("75000"), 120, PublishersBUS.getPublishersList()[2],
                                                "Vũ Minh Tú", TypesBUS.getTypesList()[4],
                                                BookFormatsBUS.getFormatsList()[5], "13 x 20 cm",
                                                GenresBUS.getGenres(10, 15)),
                                new Books("00110034", "Cuộc Sống Sáng Tạo", LocalDate.of(2021, 3, 19),
                                                new BigDecimal("105000"), 150, PublishersBUS.getPublishersList()[1],
                                                "Nguyễn Duy Khánh", TypesBUS.getTypesList()[6],
                                                BookFormatsBUS.getFormatsList()[11], "15 x 20 cm",
                                                GenresBUS.getGenres(15, 20)),
                                new Books("00110035", "Độc Lập Và Tự Do", LocalDate.of(2020, 4, 10),
                                                new BigDecimal("120000"), 200, PublishersBUS.getPublishersList()[6],
                                                "Lê Quang Tú", TypesBUS.getTypesList()[5],
                                                BookFormatsBUS.getFormatsList()[6], "14 x 22 cm",
                                                GenresBUS.getGenres(0, 4)),
                                new Books("00110036", "Kỳ Bí Của Các Hành Tinh", LocalDate.of(2023, 7, 1),
                                                new BigDecimal("150000"), 60, PublishersBUS.getPublishersList()[5],
                                                "Trần Phú Thái", TypesBUS.getTypesList()[2],
                                                BookFormatsBUS.getFormatsList()[14], "18 x 25 cm",
                                                GenresBUS.getGenres(5, 9)),
                                new Books("00110037", "Mười Điều Bí Mật", LocalDate.of(2022, 4, 12),
                                                new BigDecimal("95000"), 75, PublishersBUS.getPublishersList()[4],
                                                "Hoàng Minh Đức", TypesBUS.getTypesList()[7],
                                                BookFormatsBUS.getFormatsList()[13], "16 x 20 cm",
                                                GenresBUS.getGenres(10, 15)),
                                new Books("00110038", "Lý Thuyết Và Thực Hành Khoa Học", LocalDate.of(2023, 8, 7),
                                                new BigDecimal("110000"), 130, PublishersBUS.getPublishersList()[8],
                                                "Bùi Thị Mai", TypesBUS.getTypesList()[3],
                                                BookFormatsBUS.getFormatsList()[10], "12 x 18 cm",
                                                GenresBUS.getGenres(15, 20)),
                                new Books("00110039", "Khám Phá Những Con Đường Mới", LocalDate.of(2019, 10, 25),
                                                new BigDecimal("80000"), 160, PublishersBUS.getPublishersList()[7],
                                                "Nguyễn Hương Lan", TypesBUS.getTypesList()[0],
                                                BookFormatsBUS.getFormatsList()[17], "13 x 17 cm",
                                                GenresBUS.getGenres(20, 25)),
                                new Books("00110040", "Thế Giới Bí Ẩn", LocalDate.of(2022, 2, 5),
                                                new BigDecimal("100000"), 90, PublishersBUS.getPublishersList()[3],
                                                "Trần Mạnh Cường", TypesBUS.getTypesList()[8],
                                                BookFormatsBUS.getFormatsList()[9], "16 x 22 cm",
                                                GenresBUS.getGenres(0, 4)),
                                new Books("00110041", "Giải Mã Môi Trường Xung Quanh", LocalDate.of(2021, 12, 19),
                                                new BigDecimal("85000"), 100, PublishersBUS.getPublishersList()[0],
                                                "Lê Bảo Lâm", TypesBUS.getTypesList()[12],
                                                BookFormatsBUS.getFormatsList()[3], "14 x 20 cm",
                                                GenresBUS.getGenres(5, 9)),
                                new Books("00110042", "Những Điều Kỳ Diệu Về Động Vật", LocalDate.of(2023, 1, 12),
                                                new BigDecimal("95000"), 110, PublishersBUS.getPublishersList()[9],
                                                "Nguyễn Hải Long", TypesBUS.getTypesList()[5],
                                                BookFormatsBUS.getFormatsList()[18], "13 x 19 cm",
                                                GenresBUS.getGenres(10, 15)),
                                new Books("00110043", "Phương Pháp Giải Quyết Vấn Đề", LocalDate.of(2020, 3, 15),
                                                new BigDecimal("95000"), 120, PublishersBUS.getPublishersList()[10],
                                                "Bùi Huy Hoàng", TypesBUS.getTypesList()[4],
                                                BookFormatsBUS.getFormatsList()[8], "15 x 20 cm",
                                                GenresBUS.getGenres(15, 20)),
                                new Books("00110044", "Giải Mã Lịch Sử Nhân Loại", LocalDate.of(2021, 5, 5),
                                                new BigDecimal("110000"), 60, PublishersBUS.getPublishersList()[12],
                                                "Trần Thanh Tùng", TypesBUS.getTypesList()[1],
                                                BookFormatsBUS.getFormatsList()[16], "12 x 18 cm",
                                                GenresBUS.getGenres(5, 9)),
                                new Books("00110045", "Công Nghệ Và Tương Lai", LocalDate.of(2023, 10, 10),
                                                new BigDecimal("130000"), 150, PublishersBUS.getPublishersList()[4],
                                                "Nguyễn Minh Triều", TypesBUS.getTypesList()[2],
                                                BookFormatsBUS.getFormatsList()[1], "18 x 24 cm",
                                                GenresBUS.getGenres(10, 15)),
                                new Books("00110046", "Những Bài Học Cuộc Sống", LocalDate.of(2021, 4, 22),
                                                new BigDecimal("75000"), 180, PublishersBUS.getPublishersList()[7],
                                                "Trần Thanh Bình", TypesBUS.getTypesList()[8],
                                                BookFormatsBUS.getFormatsList()[13], "14 x 20 cm",
                                                GenresBUS.getGenres(15, 20)),
                                new Books("00110047", "Sự Sống Trong Vũ Trụ", LocalDate.of(2022, 12, 9),
                                                new BigDecimal("110000"), 90, PublishersBUS.getPublishersList()[11],
                                                "Lê Phú Tấn", TypesBUS.getTypesList()[3],
                                                BookFormatsBUS.getFormatsList()[0], "20 x 25 cm",
                                                GenresBUS.getGenres(20, 25)),
                                new Books("00110048", "Cẩm Nang Sống Vui", LocalDate.of(2019, 11, 18),
                                                new BigDecimal("95000"), 120, PublishersBUS.getPublishersList()[10],
                                                "Vũ Minh Thông", TypesBUS.getTypesList()[12],
                                                BookFormatsBUS.getFormatsList()[17], "15 x 22 cm",
                                                GenresBUS.getGenres(5, 9)),
                                new Books("00110049", "Khám Phá Biển Cả", LocalDate.of(2023, 7, 14),
                                                new BigDecimal("100000"), 60, PublishersBUS.getPublishersList()[3],
                                                "Trần Tự Tài", TypesBUS.getTypesList()[4],
                                                BookFormatsBUS.getFormatsList()[2], "14 x 18 cm",
                                                GenresBUS.getGenres(0, 4)),
                                new Books("00110050", "Bí Mật Đằng Sau Mọi Chuyện", LocalDate.of(2021, 6, 22),
                                                new BigDecimal("95000"), 80, PublishersBUS.getPublishersList()[9],
                                                "Bùi Mạnh Quân", TypesBUS.getTypesList()[1],
                                                BookFormatsBUS.getFormatsList()[14], "15 x 19 cm",
                                                GenresBUS.getGenres(5, 9)),
                                new Books("00110051", "Khám Phá Tâm Hồn", LocalDate.of(2020, 8, 3),
                                                new BigDecimal("110000"), 150, PublishersBUS.getPublishersList()[6],
                                                "Lê Thiên Lộc", TypesBUS.getTypesList()[7],
                                                BookFormatsBUS.getFormatsList()[6], "12 x 16 cm",
                                                GenresBUS.getGenres(10, 15)),
                                new Books("00110052", "Chìa Khóa Thành Công", LocalDate.of(2023, 5, 8),
                                                new BigDecimal("95000"), 120, PublishersBUS.getPublishersList()[7],
                                                "Trần Thiên Phúc", TypesBUS.getTypesList()[10],
                                                BookFormatsBUS.getFormatsList()[7], "16 x 22 cm",
                                                GenresBUS.getGenres(15, 20)),
                                new Books("00110053", "Con Đường Sự Nghiệp", LocalDate.of(2022, 1, 11),
                                                new BigDecimal("110000"), 180, PublishersBUS.getPublishersList()[9],
                                                "Nguyễn Tâm Hương", TypesBUS.getTypesList()[3],
                                                BookFormatsBUS.getFormatsList()[3], "14 x 18 cm",
                                                GenresBUS.getGenres(20, 25)),
                                new Books("00110054", "Thế Giới Quanh Ta", LocalDate.of(2021, 11, 30),
                                                new BigDecimal("105000"), 70, PublishersBUS.getPublishersList()[8],
                                                "Lê Quang Đức", TypesBUS.getTypesList()[6],
                                                BookFormatsBUS.getFormatsList()[18], "13 x 19 cm",
                                                GenresBUS.getGenres(0, 4)),
                                new Books("00110055", "Mỗi Ngày Một Câu Hỏi", LocalDate.of(2023, 9, 7),
                                                new BigDecimal("90000"), 160, PublishersBUS.getPublishersList()[10],
                                                "Nguyễn Mai Phương", TypesBUS.getTypesList()[0],
                                                BookFormatsBUS.getFormatsList()[8], "18 x 20 cm",
                                                GenresBUS.getGenres(5, 9)),
                                new Books("00110056", "Khoa Học Và Cuộc Sống", LocalDate.of(2020, 5, 13),
                                                new BigDecimal("85000"), 120, PublishersBUS.getPublishersList()[2],
                                                "Trần Kiến Giang", TypesBUS.getTypesList()[8],
                                                BookFormatsBUS.getFormatsList()[12], "14 x 21 cm",
                                                GenresBUS.getGenres(10, 15)),
                                new Books("00110057", "Sức Mạnh Của Tư Duy", LocalDate.of(2021, 2, 16),
                                                new BigDecimal("95000"), 90, PublishersBUS.getPublishersList()[4],
                                                "Nguyễn Ánh Dương", TypesBUS.getTypesList()[4],
                                                BookFormatsBUS.getFormatsList()[1], "12 x 18 cm",
                                                GenresBUS.getGenres(15, 20)),
                                new Books("00110058", "Hành Trình Đi Tìm Lý Tưởng", LocalDate.of(2023, 6, 30),
                                                new BigDecimal("100000"), 60, PublishersBUS.getPublishersList()[3],
                                                "Bùi Thanh Tâm", TypesBUS.getTypesList()[7],
                                                BookFormatsBUS.getFormatsList()[17], "14 x 22 cm",
                                                GenresBUS.getGenres(0, 4)),
                                new Books("00110059", "Tư Duy Và Quyết Định", LocalDate.of(2022, 10, 15),
                                                new BigDecimal("95000"), 130, PublishersBUS.getPublishersList()[6],
                                                "Nguyễn Thành Long", TypesBUS.getTypesList()[12],
                                                BookFormatsBUS.getFormatsList()[0], "13 x 18 cm",
                                                GenresBUS.getGenres(15, 20)),
                                new Books("00110060", "Những Bí Ẩn Của Cuộc Đời", LocalDate.of(2021, 9, 22),
                                                new BigDecimal("105000"), 200, PublishersBUS.getPublishersList()[11],
                                                "Vũ Thiên Tâm", TypesBUS.getTypesList()[1],
                                                BookFormatsBUS.getFormatsList()[14], "16 x 23 cm",
                                                GenresBUS.getGenres(20, 25)),
                                new Books("00110061", "Hóa Thân Thành Ma", LocalDate.of(2023, 1, 12),
                                                new BigDecimal("120000"), 200, PublishersBUS.getPublishersList()[3],
                                                "Keiji Tanaka", TypesBUS.getTypesList()[4],
                                                BookFormatsBUS.getFormatsList()[6], "13 x 18 cm",
                                                GenresBUS.getGenres(4, 7)),
                                new Books("00110062", "Chú Rồng Tiến Lên", LocalDate.of(2021, 3, 30),
                                                new BigDecimal("98000"), 160, PublishersBUS.getPublishersList()[5],
                                                "Saito Yamada", TypesBUS.getTypesList()[2],
                                                BookFormatsBUS.getFormatsList()[3], "15 x 22 cm",
                                                GenresBUS.getGenres(7, 11)),
                                new Books("00110063", "Tâm Hồn Hắc Ám", LocalDate.of(2020, 7, 14),
                                                new BigDecimal("85000"), 120, PublishersBUS.getPublishersList()[8],
                                                "Yuko Sato", TypesBUS.getTypesList()[7],
                                                BookFormatsBUS.getFormatsList()[1], "14 x 19 cm",
                                                GenresBUS.getGenres(8, 12)),
                                new Books("00110064", "Công Chúa Lãng Quên", LocalDate.of(2022, 10, 5),
                                                new BigDecimal("110000"), 100, PublishersBUS.getPublishersList()[9],
                                                "Rika Shirai", TypesBUS.getTypesList()[9],
                                                BookFormatsBUS.getFormatsList()[5], "13 x 18 cm",
                                                GenresBUS.getGenres(5, 8)),
                                new Books("00110065", "Thế Giới Của Những Kẻ Mơ Mộng", LocalDate.of(2023, 8, 15),
                                                new BigDecimal("125000"), 80, PublishersBUS.getPublishersList()[7],
                                                "Ryo Kisaragi", TypesBUS.getTypesList()[6],
                                                BookFormatsBUS.getFormatsList()[7], "16 x 20 cm",
                                                GenresBUS.getGenres(2, 6)),
                                new Books("00110066", "Thánh Thần Vô Tận", LocalDate.of(2021, 11, 1),
                                                new BigDecimal("115000"), 140, PublishersBUS.getPublishersList()[0],
                                                "Ichiro Morita", TypesBUS.getTypesList()[5],
                                                BookFormatsBUS.getFormatsList()[4], "18 x 24 cm",
                                                GenresBUS.getGenres(6, 10)),
                                new Books("00110067", "Ninja Và Cái Chết", LocalDate.of(2022, 4, 20),
                                                new BigDecimal("102000"), 130, PublishersBUS.getPublishersList()[6],
                                                "Kaito Sakamoto", TypesBUS.getTypesList()[1],
                                                BookFormatsBUS.getFormatsList()[13], "12 x 17 cm",
                                                GenresBUS.getGenres(9, 14)),
                                new Books("00110068", "Vương Quốc Mộng Mơ", LocalDate.of(2023, 3, 11),
                                                new BigDecimal("105000"), 120, PublishersBUS.getPublishersList()[3],
                                                "Taro Suzuki", TypesBUS.getTypesList()[2],
                                                BookFormatsBUS.getFormatsList()[6], "14 x 21 cm",
                                                GenresBUS.getGenres(7, 12)),
                                new Books("00110069", "Công Chúa Cổ Tích", LocalDate.of(2020, 6, 12),
                                                new BigDecimal("90000"), 110, PublishersBUS.getPublishersList()[4],
                                                "Mai Okamoto", TypesBUS.getTypesList()[0],
                                                BookFormatsBUS.getFormatsList()[2], "13 x 20 cm",
                                                GenresBUS.getGenres(5, 8)),
                                new Books("00110070", "Cuộc Sống Bí Ẩn", LocalDate.of(2023, 9, 28),
                                                new BigDecimal("95000"), 130, PublishersBUS.getPublishersList()[10],
                                                "Yuto Takahashi", TypesBUS.getTypesList()[8],
                                                BookFormatsBUS.getFormatsList()[8], "14 x 22 cm",
                                                GenresBUS.getGenres(12, 16)),
                                new Books("00110071", "Mặt Nạ Của Thần", LocalDate.of(2021, 5, 8),
                                                new BigDecimal("105000"), 160, PublishersBUS.getPublishersList()[1],
                                                "Natsuki Yamaguchi", TypesBUS.getTypesList()[7],
                                                BookFormatsBUS.getFormatsList()[1], "12 x 19 cm",
                                                GenresBUS.getGenres(6, 9)),
                                new Books("00110072", "Chân Trời Của Những Giấc Mơ", LocalDate.of(2023, 7, 10),
                                                new BigDecimal("98000"), 150, PublishersBUS.getPublishersList()[0],
                                                "Kiyoshi Hasegawa", TypesBUS.getTypesList()[10],
                                                BookFormatsBUS.getFormatsList()[0], "15 x 20 cm",
                                                GenresBUS.getGenres(2, 5)),
                                new Books("00110073", "Mê Cung Vô Tận", LocalDate.of(2022, 9, 17),
                                                new BigDecimal("112000"), 140, PublishersBUS.getPublishersList()[5],
                                                "Junpei Mori", TypesBUS.getTypesList()[6],
                                                BookFormatsBUS.getFormatsList()[2], "13 x 22 cm",
                                                GenresBUS.getGenres(3, 7)),
                                new Books("00110074", "Chuyện Cổ Tích Mới", LocalDate.of(2020, 3, 5),
                                                new BigDecimal("100000"), 120, PublishersBUS.getPublishersList()[6],
                                                "Eri Tanaka", TypesBUS.getTypesList()[8],
                                                BookFormatsBUS.getFormatsList()[3], "16 x 18 cm",
                                                GenresBUS.getGenres(7, 11)),
                                new Books("00110075", "Ký Ức Mất Tích", LocalDate.of(2021, 10, 22),
                                                new BigDecimal("105000"), 100, PublishersBUS.getPublishersList()[9],
                                                "Akira Nagasaki", TypesBUS.getTypesList()[3],
                                                BookFormatsBUS.getFormatsList()[7], "14 x 20 cm",
                                                GenresBUS.getGenres(10, 14)),
                                new Books("00110076", "Sức Mạnh Của Mặt Trời", LocalDate.of(2023, 5, 19),
                                                new BigDecimal("125000"), 130, PublishersBUS.getPublishersList()[8],
                                                "Haruto Ishida", TypesBUS.getTypesList()[5],
                                                BookFormatsBUS.getFormatsList()[6], "12 x 18 cm",
                                                GenresBUS.getGenres(4, 8)),
                                new Books("00110077", "Giấc Mơ Của Những Kẻ Phiêu Lưu", LocalDate.of(2022, 6, 5),
                                                new BigDecimal("115000"), 110, PublishersBUS.getPublishersList()[7],
                                                "Ryuji Hayakawa", TypesBUS.getTypesList()[2],
                                                BookFormatsBUS.getFormatsList()[10], "14 x 20 cm",
                                                GenresBUS.getGenres(11, 15)),
                                new Books("00110078", "Cuộc Đời Mới", LocalDate.of(2023, 8, 12),
                                                new BigDecimal("120000"), 90, PublishersBUS.getPublishersList()[4],
                                                "Daisuke Miyamoto", TypesBUS.getTypesList()[6],
                                                BookFormatsBUS.getFormatsList()[5], "12 x 17 cm",
                                                GenresBUS.getGenres(8, 12)),
                                new Books("00110079", "Ánh Sáng Đến Từ Vô Cùng", LocalDate.of(2021, 1, 10),
                                                new BigDecimal("115000"), 170, PublishersBUS.getPublishersList()[2],
                                                "Kenta Saito", TypesBUS.getTypesList()[7],
                                                BookFormatsBUS.getFormatsList()[9], "16 x 24 cm",
                                                GenresBUS.getGenres(5, 8)),
                                new Books("00110080", "Trái Tim Mù Quáng", LocalDate.of(2020, 10, 18),
                                                new BigDecimal("95000"), 140, PublishersBUS.getPublishersList()[3],
                                                "Hiroshi Iwakura", TypesBUS.getTypesList()[3],
                                                BookFormatsBUS.getFormatsList()[1], "14 x 19 cm",
                                                GenresBUS.getGenres(4, 9)),
                                new Books("00110081", "Thế Giới Mà Ta Tạo Ra", LocalDate.of(2023, 4, 25),
                                                new BigDecimal("105000"), 180, PublishersBUS.getPublishersList()[1],
                                                "Yuji Tanaka", TypesBUS.getTypesList()[10],
                                                BookFormatsBUS.getFormatsList()[7], "13 x 19 cm",
                                                GenresBUS.getGenres(10, 13)),
                                new Books("00110082", "Dòng Chảy Của Thời Gian", LocalDate.of(2022, 12, 21),
                                                new BigDecimal("125000"), 160, PublishersBUS.getPublishersList()[5],
                                                "Shunya Kudo", TypesBUS.getTypesList()[6],
                                                BookFormatsBUS.getFormatsList()[0], "14 x 20 cm",
                                                GenresBUS.getGenres(6, 10)),
                                new Books("00110083", "Giọng Nói Của Cái Chết", LocalDate.of(2020, 9, 2),
                                                new BigDecimal("105000"), 140, PublishersBUS.getPublishersList()[4],
                                                "Takahiro Kato", TypesBUS.getTypesList()[9],
                                                BookFormatsBUS.getFormatsList()[4], "13 x 19 cm",
                                                GenresBUS.getGenres(7, 11)),
                                new Books("00110084", "Những Người Tình Mộng Mơ", LocalDate.of(2021, 4, 9),
                                                new BigDecimal("98000"), 120, PublishersBUS.getPublishersList()[8],
                                                "Ryo Mizuki", TypesBUS.getTypesList()[7],
                                                BookFormatsBUS.getFormatsList()[2], "14 x 22 cm",
                                                GenresBUS.getGenres(9, 14)),
                                new Books("00110085", "Nơi Tận Cùng Của Mặt Trời", LocalDate.of(2023, 2, 18),
                                                new BigDecimal("130000"), 200, PublishersBUS.getPublishersList()[10],
                                                "Tatsuya Yamada", TypesBUS.getTypesList()[1],
                                                BookFormatsBUS.getFormatsList()[0], "15 x 23 cm",
                                                GenresBUS.getGenres(5, 10)),
                                new Books("00110086", "Thành Phố Mà Quái Vật Sống", LocalDate.of(2020, 11, 17),
                                                new BigDecimal("115000"), 130, PublishersBUS.getPublishersList()[3],
                                                "Keiko Yamagishi", TypesBUS.getTypesList()[4],
                                                BookFormatsBUS.getFormatsList()[6], "13 x 21 cm",
                                                GenresBUS.getGenres(6, 9)),
                                new Books("00110087", "Kẻ Dẫn Đường Mộng Mơ", LocalDate.of(2021, 6, 8),
                                                new BigDecimal("105000"), 140, PublishersBUS.getPublishersList()[2],
                                                "Eiko Ishida", TypesBUS.getTypesList()[2],
                                                BookFormatsBUS.getFormatsList()[4], "12 x 18 cm",
                                                GenresBUS.getGenres(8, 11)),
                                new Books("00110088", "Vượt Qua Thời Gian", LocalDate.of(2022, 2, 1),
                                                new BigDecimal("98000"), 120, PublishersBUS.getPublishersList()[6],
                                                "Tetsuya Hoshino", TypesBUS.getTypesList()[5],
                                                BookFormatsBUS.getFormatsList()[2], "14 x 21 cm",
                                                GenresBUS.getGenres(7, 11)),
                                new Books("00110089", "Những Kẻ Sống Lại", LocalDate.of(2021, 8, 12),
                                                new BigDecimal("105000"), 160, PublishersBUS.getPublishersList()[7],
                                                "Yoshiko Tanaka", TypesBUS.getTypesList()[3],
                                                BookFormatsBUS.getFormatsList()[5], "15 x 22 cm",
                                                GenresBUS.getGenres(5, 9)),
                                new Books("00110090", "Người Đứng Sau Bóng Tối", LocalDate.of(2023, 7, 19),
                                                new BigDecimal("110000"), 180, PublishersBUS.getPublishersList()[10],
                                                "Sanae Sato", TypesBUS.getTypesList()[0],
                                                BookFormatsBUS.getFormatsList()[3], "14 x 20 cm",
                                                GenresBUS.getGenres(6, 10)),
                                new Books("00110091", "Cuộc Chiến Của Những Kẻ Săn Mồi", LocalDate.of(2022, 5, 25),
                                                new BigDecimal("115000"), 150, PublishersBUS.getPublishersList()[5],
                                                "Hiroki Fujiwara", TypesBUS.getTypesList()[6],
                                                BookFormatsBUS.getFormatsList()[0], "13 x 21 cm",
                                                GenresBUS.getGenres(9, 14)),
                                new Books("00110092", "Dòng Sông Bất Tận", LocalDate.of(2023, 6, 1),
                                                new BigDecimal("120000"), 130, PublishersBUS.getPublishersList()[2],
                                                "Mikio Nakamura", TypesBUS.getTypesList()[7],
                                                BookFormatsBUS.getFormatsList()[9], "15 x 23 cm",
                                                GenresBUS.getGenres(7, 11)),
                                new Books("00110093", "Người Đưa Đường Tình Yêu", LocalDate.of(2020, 4, 8),
                                                new BigDecimal("98000"), 110, PublishersBUS.getPublishersList()[8],
                                                "Tatsuro Okamoto", TypesBUS.getTypesList()[10],
                                                BookFormatsBUS.getFormatsList()[4], "14 x 18 cm",
                                                GenresBUS.getGenres(4, 9)),
                                new Books("00110094", "Những Giấc Mơ Xuyên Thời Gian", LocalDate.of(2022, 8, 3),
                                                new BigDecimal("125000"), 180, PublishersBUS.getPublishersList()[4],
                                                "Rika Kudo", TypesBUS.getTypesList()[2],
                                                BookFormatsBUS.getFormatsList()[7], "12 x 20 cm",
                                                GenresBUS.getGenres(6, 12)),
                                new Books("00110095", "Khi Đêm Tàn Lụi", LocalDate.of(2021, 12, 5),
                                                new BigDecimal("105000"), 140, PublishersBUS.getPublishersList()[6],
                                                "Yusuke Fukuoka", TypesBUS.getTypesList()[4],
                                                BookFormatsBUS.getFormatsList()[1], "13 x 21 cm",
                                                GenresBUS.getGenres(3, 7)),
                                new Books("00110096", "Thế Giới Xuyên Không", LocalDate.of(2023, 9, 13),
                                                new BigDecimal("95000"), 120, PublishersBUS.getPublishersList()[10],
                                                "Junichi Sato", TypesBUS.getTypesList()[6],
                                                BookFormatsBUS.getFormatsList()[2], "16 x 24 cm",
                                                GenresBUS.getGenres(4, 8)),
                                new Books("00110097", "Người Bảo Vệ Giấc Mơ", LocalDate.of(2020, 12, 16),
                                                new BigDecimal("100000"), 130, PublishersBUS.getPublishersList()[3],
                                                "Keiko Yoshida", TypesBUS.getTypesList()[5],
                                                BookFormatsBUS.getFormatsList()[8], "15 x 22 cm",
                                                GenresBUS.getGenres(7, 10)),
                                new Books("00110098", "Hành Trình Tìm Lại Chính Mình", LocalDate.of(2022, 3, 30),
                                                new BigDecimal("110000"), 160, PublishersBUS.getPublishersList()[0],
                                                "Haruto Takami", TypesBUS.getTypesList()[3],
                                                BookFormatsBUS.getFormatsList()[10], "12 x 17 cm",
                                                GenresBUS.getGenres(8, 12)),
                                new Books("00110099", "Thực Tế Đen Tối", LocalDate.of(2021, 7, 20),
                                                new BigDecimal("115000"), 120, PublishersBUS.getPublishersList()[2],
                                                "Tomoatsu Nishida", TypesBUS.getTypesList()[6],
                                                BookFormatsBUS.getFormatsList()[5], "14 x 22 cm",
                                                GenresBUS.getGenres(6, 9)),
                                new Books("00110100", "Tình Bạn Mãi Mãi", LocalDate.of(2023, 10, 10),
                                                new BigDecimal("120000"), 140, PublishersBUS.getPublishersList()[9],
                                                "Harumi Suzuki", TypesBUS.getTypesList()[1],
                                                BookFormatsBUS.getFormatsList()[1], "13 x 18 cm",
                                                GenresBUS.getGenres(3, 7)),
                                new Books("00110101", "Nơi Cuối Cùng Của Thế Giới", LocalDate.of(2020, 11, 1),
                                                new BigDecimal("130000"), 200, PublishersBUS.getPublishersList()[6],
                                                "Yuto Kono", TypesBUS.getTypesList()[4],
                                                BookFormatsBUS.getFormatsList()[0], "12 x 18 cm",
                                                GenresBUS.getGenres(5, 9)),
                                new Books("00110102", "Giữa Chốn Mộng Mơ", LocalDate.of(2021, 9, 5),
                                                new BigDecimal("105000"), 110, PublishersBUS.getPublishersList()[5],
                                                "Akiyama Sato", TypesBUS.getTypesList()[6],
                                                BookFormatsBUS.getFormatsList()[3], "13 x 20 cm",
                                                GenresBUS.getGenres(2, 6)),
                                new Books("00110103", "Đêm Dài Cô Đơn", LocalDate.of(2023, 1, 7),
                                                new BigDecimal("110000"), 120, PublishersBUS.getPublishersList()[0],
                                                "Yuki Ito", TypesBUS.getTypesList()[3],
                                                BookFormatsBUS.getFormatsList()[7], "14 x 22 cm",
                                                GenresBUS.getGenres(8, 12)),
                                new Books("00110104", "Thần Thoại Và Những Mối Liên Kết", LocalDate.of(2022, 7, 20),
                                                new BigDecimal("120000"), 150, PublishersBUS.getPublishersList()[7],
                                                "Shinichi Fujiwara", TypesBUS.getTypesList()[9],
                                                BookFormatsBUS.getFormatsList()[10], "15 x 20 cm",
                                                GenresBUS.getGenres(4, 8)),
                                new Books("00110105", "Vùng Đất Lãng Quên", LocalDate.of(2023, 3, 18),
                                                new BigDecimal("130000"), 160, PublishersBUS.getPublishersList()[3],
                                                "Yusuke Tanimoto", TypesBUS.getTypesList()[7],
                                                BookFormatsBUS.getFormatsList()[4], "14 x 23 cm",
                                                GenresBUS.getGenres(9, 13)),
                                new Books("00110106", "Những Đoạn Ký Ức Của Cuộc Đời", LocalDate.of(2020, 5, 3),
                                                new BigDecimal("115000"), 120, PublishersBUS.getPublishersList()[8],
                                                "Masaki Okabe", TypesBUS.getTypesList()[6],
                                                BookFormatsBUS.getFormatsList()[1], "16 x 21 cm",
                                                GenresBUS.getGenres(7, 10)),
                                new Books("00110107", "Mặt Trời Mới Sáng", LocalDate.of(2022, 9, 22),
                                                new BigDecimal("125000"), 130, PublishersBUS.getPublishersList()[10],
                                                "Yuta Kamimoto", TypesBUS.getTypesList()[8],
                                                BookFormatsBUS.getFormatsList()[6], "12 x 17 cm",
                                                GenresBUS.getGenres(6, 11)),
                                new Books("00110108", "Vẫn Mãi Sống", LocalDate.of(2021, 2, 11),
                                                new BigDecimal("95000"), 140, PublishersBUS.getPublishersList()[0],
                                                "Rika Mori", TypesBUS.getTypesList()[5],
                                                BookFormatsBUS.getFormatsList()[9], "13 x 21 cm",
                                                GenresBUS.getGenres(2, 6)),
                                new Books("00110109", "Ánh Sáng Ở Cuối Đường Hầm", LocalDate.of(2023, 11, 4),
                                                new BigDecimal("110000"), 180, PublishersBUS.getPublishersList()[4],
                                                "Hiroshi Tanaka", TypesBUS.getTypesList()[9],
                                                BookFormatsBUS.getFormatsList()[3], "15 x 23 cm",
                                                GenresBUS.getGenres(5, 9)),
                                new Books("00110110", "Giấc Mơ Của Một Ngày Mới", LocalDate.of(2022, 1, 14),
                                                new BigDecimal("120000"), 130, PublishersBUS.getPublishersList()[6],
                                                "Takashi Matsumoto", TypesBUS.getTypesList()[1],
                                                BookFormatsBUS.getFormatsList()[7], "13 x 18 cm",
                                                GenresBUS.getGenres(6, 10)),
                                new Books("00110111", "Những Cuộc Đời Khác Biệt", LocalDate.of(2021, 6, 12),
                                                new BigDecimal("105000"), 140, PublishersBUS.getPublishersList()[9],
                                                "Mika Saito", TypesBUS.getTypesList()[7],
                                                BookFormatsBUS.getFormatsList()[4], "12 x 20 cm",
                                                GenresBUS.getGenres(8, 13)),
                                new Books("00110112", "Sự Sống Và Cái Chết", LocalDate.of(2023, 5, 28),
                                                new BigDecimal("125000"), 150, PublishersBUS.getPublishersList()[7],
                                                "Hiroki Matsuda", TypesBUS.getTypesList()[3],
                                                BookFormatsBUS.getFormatsList()[2], "14 x 21 cm",
                                                GenresBUS.getGenres(5, 10)),
                                new Books("00110113", "Mở Cánh Cửa Tương Lai", LocalDate.of(2020, 9, 10),
                                                new BigDecimal("115000"), 120, PublishersBUS.getPublishersList()[8],
                                                "Shinobu Hara", TypesBUS.getTypesList()[4],
                                                BookFormatsBUS.getFormatsList()[6], "13 x 22 cm",
                                                GenresBUS.getGenres(7, 12)),
                                new Books("00110114", "Trả Lại Những Giấc Mơ", LocalDate.of(2022, 11, 15),
                                                new BigDecimal("100000"), 110, PublishersBUS.getPublishersList()[5],
                                                "Keiko Fujimoto", TypesBUS.getTypesList()[6],
                                                BookFormatsBUS.getFormatsList()[0], "15 x 18 cm",
                                                GenresBUS.getGenres(6, 9)),
                                new Books("00110115", "Tình Yêu Trong Thế Giới Đảo Lộn", LocalDate.of(2021, 4, 22),
                                                new BigDecimal("130000"), 160, PublishersBUS.getPublishersList()[2],
                                                "Eri Nakajima", TypesBUS.getTypesList()[9],
                                                BookFormatsBUS.getFormatsList()[10], "13 x 20 cm",
                                                GenresBUS.getGenres(3, 7)),
                                new Books("00110116", "Khúc Hát Từ Bóng Tối", LocalDate.of(2020, 3, 15),
                                                new BigDecimal("105000"), 140, PublishersBUS.getPublishersList()[10],
                                                "Aoi Kuroki", TypesBUS.getTypesList()[5],
                                                BookFormatsBUS.getFormatsList()[3], "14 x 21 cm",
                                                GenresBUS.getGenres(8, 11)),
                                new Books("00110117", "Cánh Đồng Xanh Tươi", LocalDate.of(2023, 12, 2),
                                                new BigDecimal("120000"), 130, PublishersBUS.getPublishersList()[0],
                                                "Satoshi Morita", TypesBUS.getTypesList()[7],
                                                BookFormatsBUS.getFormatsList()[1], "13 x 19 cm",
                                                GenresBUS.getGenres(4, 8)),
                                new Books("00110118", "Tổ Chức Mật", LocalDate.of(2022, 10, 7),
                                                new BigDecimal("110000"), 150, PublishersBUS.getPublishersList()[4],
                                                "Koji Nakamura", TypesBUS.getTypesList()[6],
                                                BookFormatsBUS.getFormatsList()[7], "12 x 18 cm",
                                                GenresBUS.getGenres(6, 10)),
                                new Books("00110119", "Hình Dạng Của Niềm Tin", LocalDate.of(2023, 4, 5),
                                                new BigDecimal("115000"), 120, PublishersBUS.getPublishersList()[6],
                                                "Yuto Sakamoto", TypesBUS.getTypesList()[3],
                                                BookFormatsBUS.getFormatsList()[9], "13 x 21 cm",
                                                GenresBUS.getGenres(8, 11)),
                                new Books("00110120", "Những Điều Bí Ẩn Chưa Được Giải Thích",
                                                LocalDate.of(2021, 8, 25), new BigDecimal("120000"), 150,
                                                PublishersBUS.getPublishersList()[7], "Hiroshi Matsumoto",
                                                TypesBUS.getTypesList()[4], BookFormatsBUS.getFormatsList()[6],
                                                "14 x 22 cm", GenresBUS.getGenres(6, 10)),
                                new Books("00110089", "Những Kẻ Sống Lại", LocalDate.of(2021, 8, 12),
                                                new BigDecimal("105000"), 160, PublishersBUS.getPublishersList()[7],
                                                "Yoshiko Tanaka", TypesBUS.getTypesList()[3],
                                                BookFormatsBUS.getFormatsList()[5], "15 x 22 cm",
                                                GenresBUS.getGenres(5, 9)),
                                new Books("00110090", "Người Đứng Sau Bóng Tối", LocalDate.of(2023, 7, 19),
                                                new BigDecimal("110000"), 180, PublishersBUS.getPublishersList()[10],
                                                "Sanae Sato", TypesBUS.getTypesList()[0],
                                                BookFormatsBUS.getFormatsList()[3], "14 x 20 cm",
                                                GenresBUS.getGenres(6, 10)),
                                new Books("00110091", "Cuộc Chiến Của Những Kẻ Săn Mồi", LocalDate.of(2022, 5, 25),
                                                new BigDecimal("115000"), 150, PublishersBUS.getPublishersList()[5],
                                                "Hiroki Fujiwara", TypesBUS.getTypesList()[6],
                                                BookFormatsBUS.getFormatsList()[0], "13 x 21 cm",
                                                GenresBUS.getGenres(9, 14)),
                                new Books("00110092", "Dòng Sông Bất Tận", LocalDate.of(2023, 6, 1),
                                                new BigDecimal("120000"), 130, PublishersBUS.getPublishersList()[2],
                                                "Mikio Nakamura", TypesBUS.getTypesList()[7],
                                                BookFormatsBUS.getFormatsList()[9], "15 x 23 cm",
                                                GenresBUS.getGenres(7, 11)),
                                new Books("00110093", "Người Đưa Đường Tình Yêu", LocalDate.of(2020, 4, 8),
                                                new BigDecimal("98000"), 110, PublishersBUS.getPublishersList()[8],
                                                "Tatsuro Okamoto", TypesBUS.getTypesList()[10],
                                                BookFormatsBUS.getFormatsList()[4], "14 x 18 cm",
                                                GenresBUS.getGenres(4, 9)),
                                new Books("00110094", "Những Giấc Mơ Xuyên Thời Gian", LocalDate.of(2022, 8, 3),
                                                new BigDecimal("125000"), 180, PublishersBUS.getPublishersList()[4],
                                                "Rika Kudo", TypesBUS.getTypesList()[2],
                                                BookFormatsBUS.getFormatsList()[7], "12 x 20 cm",
                                                GenresBUS.getGenres(6, 12)),
                                new Books("00110095", "Khi Đêm Tàn Lụi", LocalDate.of(2021, 12, 5),
                                                new BigDecimal("105000"), 140, PublishersBUS.getPublishersList()[6],
                                                "Yusuke Fukuoka", TypesBUS.getTypesList()[4],
                                                BookFormatsBUS.getFormatsList()[1], "13 x 21 cm",
                                                GenresBUS.getGenres(3, 7)),
                                new Books("00110096", "Thế Giới Xuyên Không", LocalDate.of(2023, 9, 13),
                                                new BigDecimal("95000"), 120, PublishersBUS.getPublishersList()[10],
                                                "Junichi Sato", TypesBUS.getTypesList()[6],
                                                BookFormatsBUS.getFormatsList()[2], "16 x 24 cm",
                                                GenresBUS.getGenres(4, 8)),
                                new Books("00110097", "Người Bảo Vệ Giấc Mơ", LocalDate.of(2020, 12, 16),
                                                new BigDecimal("100000"), 130, PublishersBUS.getPublishersList()[3],
                                                "Keiko Yoshida", TypesBUS.getTypesList()[5],
                                                BookFormatsBUS.getFormatsList()[8], "15 x 22 cm",
                                                GenresBUS.getGenres(7, 10)),
                                new Books("00110098", "Hành Trình Tìm Lại Chính Mình", LocalDate.of(2022, 3, 30),
                                                new BigDecimal("110000"), 160, PublishersBUS.getPublishersList()[0],
                                                "Haruto Takami", TypesBUS.getTypesList()[3],
                                                BookFormatsBUS.getFormatsList()[10], "12 x 17 cm",
                                                GenresBUS.getGenres(8, 12)),
                                new Books("00110099", "Thực Tế Đen Tối", LocalDate.of(2021, 7, 20),
                                                new BigDecimal("115000"), 120, PublishersBUS.getPublishersList()[2],
                                                "Tomoatsu Nishida", TypesBUS.getTypesList()[6],
                                                BookFormatsBUS.getFormatsList()[5], "14 x 22 cm",
                                                GenresBUS.getGenres(6, 9)),
                                new Books("00110100", "Tình Bạn Mãi Mãi", LocalDate.of(2023, 10, 10),
                                                new BigDecimal("120000"), 140, PublishersBUS.getPublishersList()[9],
                                                "Harumi Suzuki", TypesBUS.getTypesList()[1],
                                                BookFormatsBUS.getFormatsList()[1], "13 x 18 cm",
                                                GenresBUS.getGenres(3, 7)),
                                new Books("00110101", "Nơi Cuối Cùng Của Thế Giới", LocalDate.of(2020, 11, 1),
                                                new BigDecimal("130000"), 200, PublishersBUS.getPublishersList()[6],
                                                "Yuto Kono", TypesBUS.getTypesList()[4],
                                                BookFormatsBUS.getFormatsList()[0], "12 x 18 cm",
                                                GenresBUS.getGenres(5, 9)),
                                new Books("00110102", "Giữa Chốn Mộng Mơ", LocalDate.of(2021, 9, 5),
                                                new BigDecimal("105000"), 110, PublishersBUS.getPublishersList()[5],
                                                "Akiyama Sato", TypesBUS.getTypesList()[6],
                                                BookFormatsBUS.getFormatsList()[3], "13 x 20 cm",
                                                GenresBUS.getGenres(2, 6)),
                                new Books("00110103", "Đêm Dài Cô Đơn", LocalDate.of(2023, 1, 7),
                                                new BigDecimal("110000"), 120, PublishersBUS.getPublishersList()[0],
                                                "Yuki Ito", TypesBUS.getTypesList()[3],
                                                BookFormatsBUS.getFormatsList()[7], "14 x 22 cm",
                                                GenresBUS.getGenres(8, 12)),
                                new Books("00110104", "Thần Thoại Và Những Mối Liên Kết", LocalDate.of(2022, 7, 20),
                                                new BigDecimal("120000"), 150, PublishersBUS.getPublishersList()[7],
                                                "Shinichi Fujiwara", TypesBUS.getTypesList()[9],
                                                BookFormatsBUS.getFormatsList()[10], "15 x 20 cm",
                                                GenresBUS.getGenres(4, 8)),
                                new Books("00110105", "Vùng Đất Lãng Quên", LocalDate.of(2023, 3, 18),
                                                new BigDecimal("130000"), 160, PublishersBUS.getPublishersList()[3],
                                                "Yusuke Tanimoto", TypesBUS.getTypesList()[7],
                                                BookFormatsBUS.getFormatsList()[4], "14 x 23 cm",
                                                GenresBUS.getGenres(9, 13)),
                                new Books("00110106", "Những Đoạn Ký Ức Của Cuộc Đời", LocalDate.of(2020, 5, 3),
                                                new BigDecimal("115000"), 120, PublishersBUS.getPublishersList()[8],
                                                "Masaki Okabe", TypesBUS.getTypesList()[6],
                                                BookFormatsBUS.getFormatsList()[1], "16 x 21 cm",
                                                GenresBUS.getGenres(7, 10)),
                                new Books("00110107", "Mặt Trời Mới Sáng", LocalDate.of(2022, 9, 22),
                                                new BigDecimal("125000"), 130, PublishersBUS.getPublishersList()[10],
                                                "Yuta Kamimoto", TypesBUS.getTypesList()[8],
                                                BookFormatsBUS.getFormatsList()[6], "12 x 17 cm",
                                                GenresBUS.getGenres(6, 11)),
                                new Books("00110108", "Vẫn Mãi Sống", LocalDate.of(2021, 2, 11),
                                                new BigDecimal("95000"), 140, PublishersBUS.getPublishersList()[0],
                                                "Rika Mori", TypesBUS.getTypesList()[5],
                                                BookFormatsBUS.getFormatsList()[9], "13 x 21 cm",
                                                GenresBUS.getGenres(2, 6)),
                                new Books("00110109", "Ánh Sáng Ở Cuối Đường Hầm", LocalDate.of(2023, 11, 4),
                                                new BigDecimal("110000"), 180, PublishersBUS.getPublishersList()[4],
                                                "Hiroshi Tanaka", TypesBUS.getTypesList()[9],
                                                BookFormatsBUS.getFormatsList()[3], "15 x 23 cm",
                                                GenresBUS.getGenres(5, 9)),
                                new Books("00110110", "Giấc Mơ Của Một Ngày Mới", LocalDate.of(2022, 1, 14),
                                                new BigDecimal("120000"), 130, PublishersBUS.getPublishersList()[6],
                                                "Takashi Matsumoto", TypesBUS.getTypesList()[1],
                                                BookFormatsBUS.getFormatsList()[7], "13 x 18 cm",
                                                GenresBUS.getGenres(6, 10)),
                                new Books("00110111", "Những Cuộc Đời Khác Biệt", LocalDate.of(2021, 6, 12),
                                                new BigDecimal("105000"), 140, PublishersBUS.getPublishersList()[9],
                                                "Mika Saito", TypesBUS.getTypesList()[7],
                                                BookFormatsBUS.getFormatsList()[4], "12 x 20 cm",
                                                GenresBUS.getGenres(8, 13)),
                                new Books("00110112", "Sự Sống Và Cái Chết", LocalDate.of(2023, 5, 28),
                                                new BigDecimal("125000"), 150, PublishersBUS.getPublishersList()[7],
                                                "Hiroki Matsuda", TypesBUS.getTypesList()[3],
                                                BookFormatsBUS.getFormatsList()[2], "14 x 21 cm",
                                                GenresBUS.getGenres(5, 10)),
                                new Books("00110113", "Mở Cánh Cửa Tương Lai", LocalDate.of(2020, 9, 10),
                                                new BigDecimal("115000"), 120, PublishersBUS.getPublishersList()[8],
                                                "Shinobu Hara", TypesBUS.getTypesList()[4],
                                                BookFormatsBUS.getFormatsList()[6], "13 x 22 cm",
                                                GenresBUS.getGenres(7, 12)),
                                new Books("00110114", "Trả Lại Những Giấc Mơ", LocalDate.of(2022, 11, 15),
                                                new BigDecimal("100000"), 110, PublishersBUS.getPublishersList()[5],
                                                "Keiko Fujimoto", TypesBUS.getTypesList()[6],
                                                BookFormatsBUS.getFormatsList()[0], "15 x 18 cm",
                                                GenresBUS.getGenres(6, 9)),
                                new Books("00110115", "Tình Yêu Trong Thế Giới Đảo Lộn", LocalDate.of(2021, 4, 22),
                                                new BigDecimal("130000"), 160, PublishersBUS.getPublishersList()[2],
                                                "Eri Nakajima", TypesBUS.getTypesList()[9],
                                                BookFormatsBUS.getFormatsList()[10], "13 x 20 cm",
                                                GenresBUS.getGenres(3, 7)),
                                new Books("00110116", "Khúc Hát Từ Bóng Tối", LocalDate.of(2020, 3, 15),
                                                new BigDecimal("105000"), 140, PublishersBUS.getPublishersList()[10],
                                                "Aoi Kuroki", TypesBUS.getTypesList()[5],
                                                BookFormatsBUS.getFormatsList()[3], "14 x 21 cm",
                                                GenresBUS.getGenres(8, 11)),
                                new Books("00110117", "Cánh Đồng Xanh Tươi", LocalDate.of(2023, 12, 2),
                                                new BigDecimal("120000"), 130, PublishersBUS.getPublishersList()[0],
                                                "Satoshi Morita", TypesBUS.getTypesList()[7],
                                                BookFormatsBUS.getFormatsList()[1], "13 x 19 cm",
                                                GenresBUS.getGenres(4, 8)),
                                new Books("00110118", "Tổ Chức Mật", LocalDate.of(2022, 10, 7),
                                                new BigDecimal("110000"), 150, PublishersBUS.getPublishersList()[4],
                                                "Koji Nakamura", TypesBUS.getTypesList()[6],
                                                BookFormatsBUS.getFormatsList()[7], "12 x 18 cm",
                                                GenresBUS.getGenres(6, 10)),
                                new Books("00110119", "Hình Dạng Của Niềm Tin", LocalDate.of(2023, 4, 5),
                                                new BigDecimal("115000"), 120, PublishersBUS.getPublishersList()[6],
                                                "Yuto Sakamoto", TypesBUS.getTypesList()[3],
                                                BookFormatsBUS.getFormatsList()[9], "13 x 21 cm",
                                                GenresBUS.getGenres(8, 11)),
                                new Books("00110120", "Những Điều Bí Ẩn Chưa Được Giải Thích",
                                                LocalDate.of(2021, 8, 25), new BigDecimal("120000"), 150,
                                                PublishersBUS.getPublishersList()[7], "Hiroshi Matsumoto",
                                                TypesBUS.getTypesList()[4], BookFormatsBUS.getFormatsList()[6],
                                                "14 x 22 cm", GenresBUS.getGenres(6, 10))

                };

                // !INIT VALUE
                listBooks.add(books);
                listBooks.showList();
                System.out.println(listBooks.getBooksList()[0].getProductID());

                // !SHOW BEFORE
                // SuppliersBUS.showList();

                // !TEST METHODS

                // !SHOW DURING
                // SuppliersBUS.showList();

                // !SHOW RESULT
                // System.out.println("------------------------AFTER(BOOK_TYPE)-----------------------");
                // TypesBUS.showList();
                // System.out.println("------------------------AFTER(BOOK_TYPE)-----------------------");
                // System.out.println("------------------------AFTER(MID)-----------------------");
                // MidForBooksBUS.showList();
                // System.out.println("------------------------AFTER(MID)-----------------------");
                // System.out.println("------------------------AFTER(STA_TYPES)-----------------------");
                // StaTypesBUS.showList();
                // System.out.println("------------------------AFTER(STA_TYPES)-----------------------");
                // System.out.println("------------------------AFTER(PUBLISHERS)-----------------------");
                // PublishersBUS.showList();
                // System.out.println("------------------------AFTER(PUBLISHERS)-----------------------");
        }
}
